// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtqrpgQGZ5otQLm6uJxvyii1UNVp-uOM4',
    appId: '1:172471767527:web:5016fa4a91ac602647ad42',
    messagingSenderId: '172471767527',
    projectId: 'fir-authentication-66ec0',
    authDomain: 'fir-authentication-66ec0.firebaseapp.com',
    storageBucket: 'fir-authentication-66ec0.firebasestorage.app',
    measurementId: 'G-XG23PY0PGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKbrx2LsjdZ9bEAIcZYzqB9lEqo1jyNbI',
    appId: '1:172471767527:android:10adfaa5b7f7314b47ad42',
    messagingSenderId: '172471767527',
    projectId: 'fir-authentication-66ec0',
    storageBucket: 'fir-authentication-66ec0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4LWPwi9qi2hVPqJX8l5hXc5W78e1rMR8',
    appId: '1:172471767527:ios:dde9a6f3c5d7bdb347ad42',
    messagingSenderId: '172471767527',
    projectId: 'fir-authentication-66ec0',
    storageBucket: 'fir-authentication-66ec0.firebasestorage.app',
    iosBundleId: 'com.example.ica16',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4LWPwi9qi2hVPqJX8l5hXc5W78e1rMR8',
    appId: '1:172471767527:ios:dde9a6f3c5d7bdb347ad42',
    messagingSenderId: '172471767527',
    projectId: 'fir-authentication-66ec0',
    storageBucket: 'fir-authentication-66ec0.firebasestorage.app',
    iosBundleId: 'com.example.ica16',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtqrpgQGZ5otQLm6uJxvyii1UNVp-uOM4',
    appId: '1:172471767527:web:babe1d2e68a5a7c647ad42',
    messagingSenderId: '172471767527',
    projectId: 'fir-authentication-66ec0',
    authDomain: 'fir-authentication-66ec0.firebaseapp.com',
    storageBucket: 'fir-authentication-66ec0.firebasestorage.app',
    measurementId: 'G-PRNBCFQEQV',
  );
}
